trigger:
  branches: 
    include:
      - main

parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: Dev
    values:
      - Dev
      - Prod

pool:
  name: "default"

variables:
#Tells Terraform that it is running in an automated environment (CI/CD)
  TF_IN_AUTOMATION: "true"
#Disables interactive input prompts. Terraform will fail immediately if a variable value is missing
  TF_INPUT: "false"
#terraform.tfvars path on agent
  BASE_TFVARS_DIR: "/home/Mrinal/Documents/VSCode/Terraform/DemoApp/DemoApp1Infra/Environments"
#part of terraform.tfvars folder path changing as per selected environment. ${{}} compile time expression
  TFVARS_PATH: "$(BASE_TFVARS_DIR)/${{ parameters.environment }}/terraform.tfvars"
#Define TF_WORKING_DIR as a pipeline variable
  TF_WORKING_DIR: "$(Build.SourcesDirectory)/DemoApp1Infra/Environments/${{ parameters.environment }}"
stages:
  - stage: terraform
    displayName: "Terraform Infra Pipeline"

    jobs:
      - job: SonarQube_Scan
        displayName: "Code quality & security check (SonarQube Community Ed)"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        # condition: and(
        #   succeeded(),
        #   eq(variables['Build.SourceBranch'], 'refs/heads/main')
        #   )

        # variables:
        #   SONARQUBE_SCANNER_PARAMS: '{}'

        steps:
          - checkout: self
            clean: true

          - script: |
              sonar-scanner \
                -Dsonar.projectKey=terraform-infra \
                -Dsonar.sources=. \
                -Dsonar.host.url=http://localhost:9000 \
                -Dsonar.login=$(SONAR_TOKEN) \
                -Dsonar.language=terraform \
                -Dsonar.terraform.provider.azure.enabled=true
            displayName: "Run SonarQube Scan (CLI)"

          # #Authenticates to SonarQube
          # #Sets environment variables
          # #Writes sonar-scanner config
          # #Prepares the workspace
          # #No scanning happens here
          # - task: SonarQubePrepare@8
          #   displayName: "Prepare SonarQube Analysis"
          #   inputs:
          #     SonarQube: 'SonarQubeServiceConnection'
          #     scannerMode: 'CLI'
          #     configMode: 'manual'
          #     cliProjectKey: 'terraform-infra'
          #     cliSources: "."
          #     extraProperties: |
          #       sonar.language=terraform
          #       sonar.terraform.provider.azure.enabled=true

          # # This task is literally the “RUN” button
          # - task: SonarQubeAnalyze@8
          #   displayName: "Run SonarQube Analysis"

          # - task: SonarQubePublish@8
          #   displayName: "Publish SonarQube Results"
          #   inputs:
          #     pollingTimeoutSec: '300'
        
          # - script: |
          #     sonar-scanner \
          #       -Dsonar.projectKey=terraform-infra \
          #       -Dsonar.sources=. \
          #       -Dsonar.host.url=http://localhost:9000
          #   displayName: Running SonarQube_Scan
          #   workingDirectory: $(TF_WORKING_DIR)




      - job: tflint
        displayName: "Terraform best practices check SAST"
        dependsOn: SonarQube_Scan 

        steps:
          - checkout: self
            clean: true

          - script: |
              tflint --init
              tflint
            displayName: "Run tflint"
            continueOnError: true
            workingDirectory: $(TF_WORKING_DIR)
          

      - job: terraform
        displayName: "Create the Azure resources"
        dependsOn: tflint

        steps:
          - checkout: self #Copy yaml dir to agents working dir
            clean: true #Clean old files from agents working dir
# cd $(TF_WORKING_DIR)         
          - script: |
              terraform init
            displayName: "Terraform Init"
            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              terraform validate
            displayName: "Terraform Validate"
            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              terraform plan -var-file=$(TFVARS_PATH)
            displayName: "Terraform PLAN"
            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              terraform apply -var-file=$(TFVARS_PATH) --auto-approve
            displayName: "Terraform Apply"
            workingDirectory: $(TF_WORKING_DIR)

          # - script: |
          #     terraform destroy -var-file=$(TFVARS_PATH) --auto-approve
          #   displayName: "Destroy All created resources"
          #   workingDirectory: $(TF_WORKING_DIR)

