trigger:
  branches:
    include:
      - main

parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: Dev
    values:
      - Dev
      - Prod

pool: default 

variables:
  TF_IN_Automation: "true"
  TF_INPUT: "false"
  BASE_TFVARS_DIR: "/home/Mrinal/Documents/VSCode/Terraform/DemoApp/DemoApp1Infra/Environments"
  TFVARS_PATH: "$(BASE_TFVARS_DIR)/${{parameters.environment}}/terraform.tfvars"

stages:
  - stage: terraform
    displayName: "Run the selected environment terraform code"


    jobs:
      - job: terraform
        displayName: "Create the Azure resources"

        steps:
          - checkout: self
            clean: true
        
          - script: |
              cd $(TF_WORKING_DIR) 
              terraform init -var-file=$(TFVAR_PATH)
            displayName: "Terraform Init"

          - script: |
              cd $(TF_WORKING_DIR)
              terraform validate -var-file=$(TFVARS_PATH)
            displayName: "Terraform Validate"
          
          - script: |
              cd $(TF_WORKING_DIR)
              tflint --init
              tflint
            displayName: "TFlint Scanning"

          - script: |
              cd $(TF_WORKING_DIR)
              terraform plan -var-file=$(TFVARS_PATH)
            displayName: "Terraform PLAN"

          - script: |
              cd $(TF_WORKING_DIR)
              terraform apply -var-file=$(TFVARS_PATH)
              -- auto-approve
            displayName: "Terraform Apply with auto apptove"
            










