trigger:
  branches:
    include:
      - main

parameters:
  - name: environment
    displayName:
    type: string
    default: Dev
    values:
      - Dev
      - Prod

pool:
  name: "Azure Pipelines"

variables:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

stages:
  - stage: Terraform
    displayName: "Run the selected environment terraform code"

    jobs:
      - job: terraform
        displayName: "Create resources as per the selected environment"

        steps:
          - checkout: self
            clean: true
          - script: |
              if [ "${{ parameters.environment }}" = "Dev" ]; then
                echo "##vso[task.setvariable variable=TF_WORKING_DIR]Dev"
                echo "##vso[task.setvariable variable=TFVARS_PATH]/home/Mrinal/Documents/VSCode/Terraform/DemoApp/DemoApp1Infra/Dev/terraform.tfvars"
              else
                echo "##vso[task.setvariable variable=TF_WORKING_DIR]Prod"
                echo "##vso[task.setvariable variable=TFVARS_PATH]/home/Mrinal/Documents/VSCode/Terraform/DemoApp/DemoApp1Infra/Prod/terraform.tfvars"
              fi
            displayName: "Select environment folder and its corresponding terraform.tfvars from local computer"
          - script: |
              cd $(TF_WORKING_DIR)
              terraform init
          - script: |
              cd $(TF_WORKING_DIR)
              terraform validate
          - script: |
              cd $(TF_WORKING_DIR)
              tflint --init
              tflint
          - script: |
              cd $(TF_WORKING_DIR)
              terraform plan \
                -var-file="$(TFVARS_PATH)" \
                -out=tfplan
          - script: |
              cd $(TF_WORKING_DIR)
              terraform apply \
                -var-file="$(TFVARS_PATH)" \
                --auto-approve
            displayName: "Terraform Apply"
