trigger:
  branches: 
    include:
      - main

parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: Dev
    values:
      - Dev
      - Prod

pool:
  name: "default"

variables:
  TF_IN_AUTOMATION: "true" #Tells Terraform that it is running in an automated environment (CI/CD)
  TF_INPUT: "false"   #Disables interactive input prompts. Terraform will fail immediately if a variable value is missing
  #terraform.tfvars path on agent
  BASE_TFVARS_DIR: "/home/Mrinal/Documents/VSCode/Terraform/DemoApp/DemoApp1Infra/Environments"
  #part of terraform.tfvars folder path changing as per selected environment
  TFVARS_PATH: "$(BASE_TFVARS_DIR)/${{ parameters.environment }}/terraform.tfvars" #${{}} compile time expression
  TF_WORKING_DIR: "$(Build.SourcesDirectory)/${{ parameters.environment }}" #Define TF_WORKING_DIR as a pipeline variable

stages:
  - stage: terraform
    displayName: "Run the selected environment terraform code"


    jobs:
      - job: terraform
        displayName: "Create the Azure resources"

        steps:
          - checkout: self
            clean: true
        
          - script: |
              cd $(TF_WORKING_DIR) 
              terraform init -var-file=$(TFVAR_PATH)
            displayName: "Terraform Init"

          - script: |
              terraform validate -var-file=$(TFVARS_PATH)
            displayName: "Terraform Validate"
            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              tflint --init
              tflint
            displayName: "Tflint scanning"

            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              terraform plan -var-file=$(TFVARS_PATH)
            displayName: "Terraform PLAN"
            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              terraform apply -var-file=$(TFVARS_PATH) --auto-approve
            displayName: "Terraform Apply"
            workingDirectory: $(TF_WORKING_DIR)
