trigger:
  branches: 
    include:
      - main

parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: Dev
    values:
      - Dev
      - Prod

pool:
  name: "default"

variables:
#Tells Terraform that it is running in an automated environment (CI/CD)
  TF_IN_AUTOMATION: "true"
#Disables interactive input prompts. Terraform will fail immediately if a variable value is missing
  TF_INPUT: "false"
#terraform.tfvars path on agent
  BASE_TFVARS_DIR: "/home/Mrinal/Documents/VSCode/Terraform/DemoApp/DemoApp1Infra/Environments"
#part of terraform.tfvars folder path changing as per selected environment. ${{}} compile time expression
  TFVARS_PATH: "$(BASE_TFVARS_DIR)/${{ parameters.environment }}/terraform.tfvars"
#Define TF_WORKING_DIR as a pipeline variable
  TF_WORKING_DIR: "$(Build.SourcesDirectory)/DemoApp1Infra/Environments/${{ parameters.environment }}"
stages:
  - stage: terraform
    displayName: "Run the selected environment terraform code"


    jobs:
      - job: terraform
        displayName: "Create the Azure resources"

        steps:
          - checkout: self #Copy yaml dir to agents working dir
            clean: true #Clean old files from agents working dir
# cd $(TF_WORKING_DIR)         
          - script: |
              terraform init
            displayName: "Terraform Init"
            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              terraform validate
            displayName: "Terraform Validate"
            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              tflint --init
              tflint
            displayName: "Tflint scanning"
            continueOnError: true

            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              terraform plan -var-file=$(TFVARS_PATH)
            displayName: "Terraform PLAN"
            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              terraform apply -var-file=$(TFVARS_PATH) --auto-approve
            displayName: "Terraform Apply"
            workingDirectory: $(TF_WORKING_DIR)

          - script: |
              terraform destroy \ -var-file=terraform.tfvars \ --auto-approve
            displayName: "Destroy All created resources"
            workingDirectory: $(TF_WORKING_DIR)

